name: ci

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x, 24.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: ${{ matrix.os }} / Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends graphviz
          npm install
          npm run test
          npm run debug
          npm run generate
